---
title: "Kendall, korelacja, zmienność"
output: html_notebook
---

```{r}
# ===============================================================
# MACIERZ ODLEGŁOŚCI KENDALLA 
# ===============================================================

n_rank <- length(S_unique)

kendall_mat <- matrix(0, nrow = n_rank, ncol = n_rank)

for(i in 1:n_rank){
  for(j in 1:n_rank){
    kendall_mat[i, j] <- kendall_tau(S_unique[[i]], S_unique[[j]])
  }
}


colnames(kendall_mat) <- paste0("R", 1:n_rank)
rownames(kendall_mat) <- paste0("R", 1:n_rank)


cat("\n--- MACIERZ ODLEGŁOŚCI KENDALLA ---\n\n")

cat(sprintf("%4s", ""), paste(sprintf("%4s", paste0("R", 1:n_rank)), collapse=""), "\n")


for(i in 1:n_rank){
  cat(sprintf("%4s", paste0("R", i)))
  cat(paste(sprintf("%4d", kendall_mat[i, ]), collapse=""))
  cat("\n")
}

```

```{r}
# ===============================================================
# MACIERZ KORELACJI
# ===============================================================

library(ggplot2)
library(reshape2)


cor_matrix <- cor(data_vars, use = "complete.obs")

cor_matrix[lower.tri(cor_matrix)] <- NA

cor_long <- melt(cor_matrix, na.rm = TRUE)

p <- ggplot(cor_long, aes(x = Var1, y = Var2, fill = value)) +
  geom_tile(color = "white") +
  geom_text(aes(label = ifelse(abs(value) > 0.8, round(value, 2), NA)),
            size = 3, na.rm = TRUE) +
  scale_fill_gradient2(low = "blue", mid = "white", high = "red",
                       midpoint = 0, limit = c(-1,1), name = "Korelacja") +
  scale_x_discrete(position = "top") +
  theme_minimal() +
  theme(
    axis.title = element_blank(),
    axis.text.x = element_text(angle = 45, vjust = 0, hjust = 0)
  ) +
  coord_fixed()

p

ggsave("macierz_korelacji.png", plot = p, width = 8, height = 6, dpi = 300)


```

```{r}
# ===============================================================
# WSPÓŁCZYNNIK ZMIENNOŚCI (CV)
# ===============================================================

X <- data_vars  

cv_table <- data.frame(
  Zmienna = colnames(X),
  Srednia = round(colMeans(X, na.rm = TRUE), 2),
  Odchylenie = round(apply(X, 2, sd, na.rm = TRUE), 2),
  CV = round(apply(X, 2, function(x) sd(x, na.rm = TRUE) / mean(x, na.rm = TRUE)), 3)
)

cv_table
```

